- name: Create postgresql_action_list
  ansible.builtin.set_fact:
    postgresql_action_list: "{{ postgresql_actions.split(',') }}"

- name: Validate postgresql_action_list
  ansible.builtin.assert:
    that:
      - postgresql_action_list | length > 0
      - postgresql_action_list | difference(postgresql_supported_actions) | length == 0

- name: Deploy PostgreSQL
  ansible.builtin.include_tasks: "{{ task_name }}.yml"
  loop: "{{ postgresql_action_list }}"
  loop_control:
    loop_var: task_name
