- name: Validate variables for replication.yml task
  ansible.builtin.assert:
    that:
      - postgresql_role is defined
      - postgresql_role in postgresql_supported_roles
      - postgresql_replication_slot is defined
      - postgresql_replication_username is defined
      - postgresql_replication_password is defined
      - postgresql_peer_ip is defined
      - postgresql_data_dir is defined

- name: Actions for primary node
  when: postgresql_role == "primary"
  become: true
  become_user: postgres
  vars:
    ansible_pipelining: true
  block:
    - name: Configure replication user
      community.postgresql.postgresql_user:
        name: "{{ postgresql_replication_username }}"
        password: "{{ postgresql_replication_password }}"
        role_attr_flags: REPLICATION,LOGIN
        state: present
      no_log: true

    - name: Create replication slot
      community.postgresql.postgresql_slot:
        name: "{{ postgresql_replication_slot }}"
        slot_type: physical
        state: present
      no_log: true

- name: Actions for replica node
  when: postgresql_role == "replica"
  block:
    - name: Stop PostgreSQL daemon
      ansible.builtin.service:
        name: postgresql
        state: stopped

    - name: Get stat for "{{ postgresql_data_dir }}"
      ansible.builtin.stat:
        path: "{{ postgresql_data_dir }}"
      register: postgresql_data_dir_stat

    - name: Backup of "{{ postgresql_data_dir }}"
      when: postgresql_data_backup
      ansible.builtin.command: "mv {{ postgresql_data_dir }} {{ postgresql_data_dir }}_backup_{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
      changed_when: true

    - name: Remove old data directory
      ansible.builtin.file:
        path: "{{ postgresql_data_dir }}"
        state: absent

    - name: Recreate data directory
      ansible.builtin.file:
        path: "{{ postgresql_data_dir }}"
        state: directory
        owner: "{{ postgresql_data_dir_stat.stat.pw_name }}"
        group: "{{ postgresql_data_dir_stat.stat.gr_name }}"
        mode: "{{ postgresql_data_dir_stat.stat.mode }}"

    - name: Create .pgpass for replication user
      ansible.builtin.copy:
        dest: "/var/lib/postgresql/.pgpass"
        owner: postgres
        group: postgres
        mode: "0600"
        content: "{{ postgresql_peer_ip }}:5432:*:{{ postgresql_replication_username }}:{{ postgresql_replication_password }}"
      no_log: true

    - name: Run pg_basebackup to initialize standby
      ansible.builtin.command:
        cmd: >
          sudo -u postgres pg_basebackup
          -h {{ postgresql_peer_ip }}
          -D {{ postgresql_data_dir }}
          -U {{ postgresql_replication_username }}
          -Fp -R -w -X stream
          --slot={{ postgresql_replication_slot }}
      changed_when: false
      async: 7200
      poll: 30

    - name: Starting PostgreSQL daemon
      ansible.builtin.service:
        name: postgresql
        state: started
