---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: primary
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /lib/systemd/systemd
    network: pgnet
  - name: replica
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /lib/systemd/systemd
    network: pgnet
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
