---
- name: Gather facts from all hosts
  hosts: all
  gather_facts: true

- name: Setup primary
  hosts: primary
  gather_facts: false
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
      vars:
        postgresql_actions: install,upload_config,state_control,deploy_users,replication
        postgresql_role: primary
        postgresql_state: restarted
        postgresql_users:
          - name: replicator
            password: replicatorpassword
            role_attr_flags: REPLICATION,LOGIN
        postgresql_replication_slots:
          - name: replica_slot
        postgresql_config:
          main:
            data_directory: "'/var/lib/postgresql/16/main'"
            hba_file: "'/etc/postgresql/16/main/pg_hba.conf'"
            ident_file: "'/etc/postgresql/16/main/pg_ident.conf'"
            listen_addresses: "'*'"
            wal_level: replica
            max_wal_senders: 3
            max_replication_slots: 1
          hba:
            - "local   all             all                                     trust"
            - "host    all             all             127.0.0.1/32            trust"
            - "host    replication     replicator      0.0.0.0/0               md5"

- name: Setup replica
  hosts: replica
  gather_facts: false
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
      vars:
        postgresql_actions: install,replication,state_control
        postgresql_role: replica
        postgresql_state: restarted
        postgresql_replication_slot: replica_slot
        postgresql_replication_username: replicator
        postgresql_replication_password: replicatorpassword
        postgresql_peer_ip: primary
        postgresql_data_backup: false
