---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    postgresql_expected_major_version: 16
  tasks:
    - name: Run install assertions
      ansible.builtin.import_tasks: ../common/tasks/assert_install.yml
